### PR TITLE
Ft get a specific party endpoint 163519260

### PR DESCRIPTION
**Pull request by fantastic-genius**
#### What does this PR do?
To create endpoint for getting a specific party
#### Description of Task to be completed?
wrote a function to get a specific party by id in the controller
Created the endpoint route in the route file
#### How should this be manually tested?
BASE_URL/api/v1/parties/1
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
#163519260
#### Screenshots (if appropriate)
None
#### Questions:
None

### CODE REVIEW

**Review by veeqtor — COMMENTED** [review]
Nice work @fantastic-genius , Please arrange your directories, so as to separate the server from the UI

**Comment by fantastic-genius** [comment]
> Nice work @fantastic-genius , Please arrange your directories, so as to separate the server from the UI

Ok thanks, I will work on this

**Comment by veeqtor** [comment]
You can now go ahead and merge

**Comment by fantastic-genius** [comment]
> You can now go ahead and merge

ok. thanks

**Pull request merged**
