### PR TITLE
Fx changes to ui pages

### PR DESCRIPTION
**Pull request by fantastic-genius**
#### What does this PR do?
Make changes to UI pages based on LFA feedback
#### Description of Task to be completed?
- Name made editable for users
- Submit buttons background takes "bluish" background *
- Tables should take more spaces within the content container *
- The headings for each content was made distinctive and increase its top padding *
- The profile image & name  placed at the top of sidebar *
- 'User Dashboard' made be big enough and distinctive. Also, it is made to be horizontally align with logout button 
- Increase the spacing between the sidebar menus and add indicator to show which menu user is hovering on
- Buttons centered aligned around input fields
- Improved landing page by giving a better descriptive outlook about the application
#### How should this be manually tested?
landing page: https://fantastic-genius.github.io/politico
admin dashboard: https://fantastic-genius.github.io/politico/UI/political-parties.html
user dashboard: https://fantastic-genius.github.io/politico/UI/vote.html
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
None
#### Screenshots (if appropriate)
None
#### Questions:
None

### CODE REVIEW

**Comment by veeqtor** [comment]
Good job @fantastic-genius, However you can improve the landing page by changing the font color of the Title and the buttons to something that will make it stand out from the background image.

**Comment by fantastic-genius** [comment]
> Good job @fantastic-genius, However you can improve the landing page by changing the font color of the Title and the buttons to something that will make it stand out from the background image.
> `white` Preferably.

Ok thanks for the review, I will look into it soonest and get back to you

**Comment by veeqtor** [comment]
Looks Good, you can go ahead and merge.

**Comment by fantastic-genius** [comment]
> Looks Good, you can go ahead and merge.

Ok. thanks for the review and commendation

**Pull request merged**
